# Site settings
title: "Code Log"
email: shadowlightwolf89@gmail.com
description: "A Jekyll Code Log."
baseurl: "/code-log"
destination: "../pages"
title_description: "A simple Jekyll blog to house code snippets and links."
title_image: "https://avatars1.githubusercontent.com/u/12989992?v=3&s=460"
google_analytics: ""
disqus_account: 
github_repository: https://github.com/shadowlightwolf89/code-log
addthis_id: 
post_limit: 5

# Social usernames/URLs
twitter_username: shadowlightwolf
github_username:  shadowlightwolf89
linkedin_link:
google_plus_link:
stackoverflow_link:

# Footer
footer_left: "Made with <i class=\"fa fa-heart\"></i> by Rowan"
footer_right: "&lt;/&gt; using the <a href=\"https://github.com/jacobtomlinson/carte-noire\">Cartte Noir</a> theme &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
permalink: pretty
exclude: [vendor]
